openapi: '3.0.2'
info:
  title: Example API
  version: '1.0'
servers:
  - url: https://api.server.test/v1

paths:
  /test:
    get:
      responses:
        404:
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  
  responses:
    NotFound:
      description: 404 response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
